name: Testes e Cobertura

on: [push]  # Executar o workflow em cada push para o repositório

jobs:
  testes-e-cobertura:
    name: Testes e Cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Versão 11 do Java
          distribution: 'adopt'  # Escolha 'adopt' ou 'temurin', ou outro distribuidor suportado

      - name: Configurar JAVA_HOME
        run: echo "JAVA_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV

      - name: Configurar Maven
        run: echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository'" >> $GITHUB_ENV

      - name: Verificar variável de ambiente JAVA_HOME
        run: echo $JAVA_HOME

      - name: Compilar e Testar a aplicação
        run: mvn clean package

      - name: Executar os testes com PITest
        run: mvn org.pitest:pitest-maven:mutationCoverage

      - name: Publicar relatório de cobertura
        uses: actions/upload-artifact@v2
        with:
          name: pitest-report
          path: target/pit-reports/
